#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generic single-GPU Federated Averaging (FedAvg) for nnU-Net v2 with
validation-metric-weighted aggregation.

This public/shareable script trains multiple nnU-Net v2 client datasets
sequentially on one GPU. After each local training step, it evaluates the local
model on that client's validation split using official nnU-Net v2 prediction and
evaluation commands. The client validation Dice scores can then be used as
aggregation weights for subsequent FedAvg rounds.

Workflow per round:
  1. Start from the previous global checkpoint.
  2. Train each client dataset sequentially with the same global initialization.
  3. Export each local model into an nnU-Net-compatible results tree.
  4. Predict each client's validation set and compute validation Dice.
  5. Aggregate local checkpoints with FedAvg:
       - round 1 may use case-count weights or Dice weights;
       - later rounds use validation-Dice weights by default.
  6. Export the resulting global checkpoint for inference with nnUNetv2_predict.

Before running, prepare:
  1. nnU-Net v2 raw, preprocessed, and results directories.
  2. Client datasets in nnU-Net v2 format.
  3. Valid ``splits_final.json`` files for all client datasets.
  4. A shared model setup across all clients:
       same configuration, trainer, plans, fold, modalities, and label schema.
  5. Either:
       --init_global <PATH_TO_INITIAL_CHECKPOINT.pth>
     or:
       --init_from_dataset_all <DATASET_ID_WITH_PRETRAINED_ALL_FOLD_MODEL>

Example command with placeholders:
  python nnunetv2_fedavg_validation_weighted.py \
    --fl_root <PATH_TO_FL_OUTPUT_DIRECTORY> \
    --raw_data_root <PATH_TO_NNUNET_RAW> \
    --results_root <PATH_TO_NNUNET_RESULTS> \
    --nnUNet_preprocessed <PATH_TO_NNUNET_PREPROCESSED> \
    --datasets <CLIENT_DATASET_ID_1> <CLIENT_DATASET_ID_2> \
    --rounds <NUMBER_OF_FL_ROUNDS> \
    --config <NNUNET_CONFIG> \
    --trainer <TRAINER_NAME> \
    --plans <PLANS_NAME> \
    --fold <FOLD_ID> \
    --init_global <PATH_TO_INITIAL_CHECKPOINT.pth>

Notes:
  - This script intentionally contains no personal paths, usernames, or
    institution-specific identifiers.
  - Dataset export IDs are generated by configurable generic formulas:
       global_id = --global_id_offset + round
       local_id  = dataset_id * --local_id_multiplier + round
  - Use ``--dry_run`` first to inspect commands before launching training.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import torch




# =========================
# Helpers
# =========================
def run_cmd(cmd: List[str], env: Optional[Dict[str, str]] = None, dry_run: bool = False) -> None:
    print("\n[CMD]", " ".join(cmd))
    if dry_run:
        print("[DRY RUN] skipped")
        return
    subprocess.run(cmd, env=env, check=True)


def newest_file(files: List[Path]) -> Path:
    files = [f for f in files if f.exists()]
    if not files:
        raise FileNotFoundError("No candidate files found")
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0]


def safe_rm_tree(p: Path) -> None:
    if p.is_symlink() or p.is_file():
        p.unlink(missing_ok=True)
        return
    if p.is_dir():
        shutil.rmtree(p)


def find_dataset_folder(root: Path, dataset_id: int) -> str:
    pat = f"Dataset{dataset_id:03d}_*"
    matches = sorted([p.name for p in root.glob(pat) if p.is_dir()])
    if not matches:
        raise FileNotFoundError(f"Cannot find {pat} under {root}")
    if len(matches) > 1:
        print(f"[WARN] Multiple matches for dataset {dataset_id}: {matches}. Using the first one.")
    return matches[0]


def count_cases_in_imagesTr(raw_data_root: Path, dataset_folder: str) -> int:
    imagesTr = raw_data_root / dataset_folder / "imagesTr"
    if not imagesTr.exists():
        raise FileNotFoundError(f"imagesTr not found: {imagesTr}")

    rx = re.compile(r"^(?P<case>.+)_(?P<mod>\d{4})\.nii(\.gz)?$")
    cases = set()
    for f in imagesTr.iterdir():
        if f.is_file():
            m = rx.match(f.name)
            if m:
                cases.add(m.group("case"))

    if cases:
        return len(cases)

    # fallback (less reliable for multi-modality)
    all_nii = [x for x in imagesTr.iterdir()
               if x.is_file() and (x.name.endswith(".nii.gz") or x.name.endswith(".nii"))]
    if not all_nii:
        raise RuntimeError(f"No nii(.gz) files found in {imagesTr}")
    print("[WARN] Could not parse case ids by nnU-Net pattern; fallback to file count.")
    return len(all_nii)


def nnunet_cfg_dir(results_root: Path, dataset_folder: str, trainer: str, plans: str, config: str) -> Path:
    return results_root / dataset_folder / f"{trainer}__{plans}__{config}"


def nnunet_fold_dir(cfg_dir: Path, fold: int) -> Path:
    return cfg_dir / f"fold_{fold}"


def pick_checkpoint_from_tree(search_root: Path) -> Path:
    """
    Prefer final > best > latest
    """
    priority = ["checkpoint_final.pth", "checkpoint_best.pth", "checkpoint_latest.pth"]
    for name in priority:
        cands = list(search_root.rglob(name))
        if cands:
            return newest_file(cands)
    raise FileNotFoundError(f"No checkpoint*.pth found under {search_root}")


def ensure_checkpoint_final(folder: Path) -> None:
    """
    Ensure checkpoint_final.pth exists in folder. Create from best/latest if missing.
    folder: fold_0 directory OR all directory
    """
    final_p = folder / "checkpoint_final.pth"
    if final_p.exists():
        return
    for alt in ["checkpoint_best.pth", "checkpoint_latest.pth"]:
        alt_p = folder / alt
        if alt_p.exists():
            shutil.copy2(alt_p, final_p)
            print(f"[FIX] Created {final_p} from {alt_p}")
            return
    raise FileNotFoundError(f"No checkpoint_best/latest to create final in: {folder}")


def copy_cfg_and_fold(src_results_root: Path,
                      src_dataset_folder: str,
                      dst_results_root: Path,
                      trainer: str,
                      plans: str,
                      config: str,
                      fold: int,
                      overwrite: bool) -> Path:
    """
    Copy ONLY the needed cfg files + fold_0 directory from src_results_root to dst_results_root.
    Returns dst fold dir.
    """
    src_cfg = nnunet_cfg_dir(src_results_root, src_dataset_folder, trainer, plans, config)
    src_fold = nnunet_fold_dir(src_cfg, fold)
    if not src_cfg.exists() or not src_fold.exists():
        raise FileNotFoundError(f"Source cfg/fold missing:\n  {src_cfg}\n  {src_fold}")

    dst_cfg = nnunet_cfg_dir(dst_results_root, src_dataset_folder, trainer, plans, config)
    dst_fold = nnunet_fold_dir(dst_cfg, fold)

    if dst_cfg.exists():
        if overwrite:
            safe_rm_tree(dst_cfg.parent)
        else:
            raise FileExistsError(f"Destination exists: {dst_cfg.parent} (use --overwrite)")

    dst_cfg.mkdir(parents=True, exist_ok=True)

    # copy cfg-level files
    for item in src_cfg.iterdir():
        if item.is_file():
            shutil.copy2(item, dst_cfg / item.name)

    # copy fold dir
    shutil.copytree(src_fold, dst_fold)

    return dst_fold


def copy_model_tree(src_results_root: Path,
                    src_dataset_id: int,
                    raw_data_root: Path,
                    dst_results_root: Path,
                    dst_dataset_folder: str,
                    trainer: str,
                    plans: str,
                    config: str,
                    fold: int,
                    overwrite: bool) -> Path:
    """
    Copy a trained model tree from src_results_root/<DatasetXXX_name> to dst_results_root/dst_dataset_folder
    keeping nnU-Net structure. Returns destination fold directory path.
    """
    src_folder = find_dataset_folder(raw_data_root, src_dataset_id)
    src_cfg = nnunet_cfg_dir(src_results_root, src_folder, trainer, plans, config)
    src_fold = nnunet_fold_dir(src_cfg, fold)
    if not src_cfg.exists() or not src_fold.exists():
        raise FileNotFoundError(f"Source model tree not found:\n  {src_cfg}\n  {src_fold}")

    dst_cfg = nnunet_cfg_dir(dst_results_root, dst_dataset_folder, trainer, plans, config)
    dst_fold = nnunet_fold_dir(dst_cfg, fold)

    if dst_cfg.exists():
        if overwrite:
            safe_rm_tree(dst_cfg.parent)
        else:
            raise FileExistsError(f"Destination already exists: {dst_cfg.parent} (use --overwrite)")

    dst_cfg.mkdir(parents=True, exist_ok=True)

    # copy config-level files
    for item in src_cfg.iterdir():
        if item.is_file():
            shutil.copy2(item, dst_cfg / item.name)

    # copy fold dir
    shutil.copytree(src_fold, dst_fold)
    return dst_fold


def export_global_from_template(global_ckpt: Path,
                               template_dataset_folder: str,
                               results_root: Path,
                               new_dataset_folder: str,
                               trainer: str,
                               plans: str,
                               config: str,
                               fold: int,
                               overwrite: bool) -> Path:
    """
    Create a new Dataset<ID>_* in default results by copying the template model tree,
    then overwrite fold checkpoint_final.pth with global checkpoint.
    """
    template_cfg = nnunet_cfg_dir(results_root, template_dataset_folder, trainer, plans, config)
    template_fold = nnunet_fold_dir(template_cfg, fold)
    if not template_cfg.exists() or not template_fold.exists():
        raise FileNotFoundError(f"Template model tree missing:\n  {template_cfg}\n  {template_fold}")

    new_cfg = nnunet_cfg_dir(results_root, new_dataset_folder, trainer, plans, config)
    new_fold = nnunet_fold_dir(new_cfg, fold)

    if new_cfg.exists():
        if overwrite:
            safe_rm_tree(new_cfg.parent)
        else:
            raise FileExistsError(f"Destination exists: {new_cfg.parent} (use --overwrite)")

    new_cfg.mkdir(parents=True, exist_ok=True)

    # copy cfg-level files
    for item in template_cfg.iterdir():
        if item.is_file():
            shutil.copy2(item, new_cfg / item.name)

    shutil.copytree(template_fold, new_fold)

    # overwrite checkpoint_final
    shutil.copy2(global_ckpt, new_fold / "checkpoint_final.pth")
    # ensure final exists (already), but keep tidy if best/latest exist
    ensure_checkpoint_final(new_fold)
    return new_fold


# =========================
# Splits & evaluation
# =========================
def load_splits_val_cases(nnUNet_preprocessed_root: Path, dataset_id: int, fold: int) -> List[str]:
    pre_folder = find_dataset_folder(nnUNet_preprocessed_root, dataset_id)
    splits_file = nnUNet_preprocessed_root / pre_folder / "splits_final.json"
    if not splits_file.exists():
        raise FileNotFoundError(f"splits_final.json not found: {splits_file}")
    splits = json.loads(splits_file.read_text())
    if not isinstance(splits, list) or fold >= len(splits):
        raise RuntimeError(f"Invalid splits_final.json or fold out of range: fold={fold}, file={splits_file}")
    fold_split = splits[fold]
    val_cases = fold_split.get("val", [])
    if not isinstance(val_cases, list) or not val_cases:
        raise RuntimeError(f"Empty/invalid val split for fold {fold}: {splits_file}")
    return val_cases


def build_val_symlink_folders(raw_data_root: Path,
                              dataset_id: int,
                              val_cases: List[str],
                              out_root: Path,
                              overwrite: bool) -> Tuple[Path, Path]:
    dataset_folder = find_dataset_folder(raw_data_root, dataset_id)
    imagesTr = raw_data_root / dataset_folder / "imagesTr"
    labelsTr = raw_data_root / dataset_folder / "labelsTr"
    if not imagesTr.exists() or not labelsTr.exists():
        raise FileNotFoundError(f"imagesTr/labelsTr missing under {raw_data_root}/{dataset_folder}")

    img_out = out_root / "imagesTs"
    lab_out = out_root / "labelsTs"

    if out_root.exists() and overwrite:
        safe_rm_tree(out_root)

    img_out.mkdir(parents=True, exist_ok=True)
    lab_out.mkdir(parents=True, exist_ok=True)

    for case in val_cases:
        # images
        candidates = list(imagesTr.glob(f"{case}_*.nii.gz")) + list(imagesTr.glob(f"{case}_*.nii"))
        if not candidates:
            raise FileNotFoundError(f"No image files for case '{case}' in {imagesTr}")
        for f in candidates:
            dst = img_out / f.name
            if not dst.exists():
                dst.symlink_to(f)

        # label
        lab_candidates = list(labelsTr.glob(f"{case}.nii.gz")) + list(labelsTr.glob(f"{case}.nii"))
        if not lab_candidates:
            raise FileNotFoundError(f"No label file for case '{case}' in {labelsTr}")
        lf = lab_candidates[0]
        dstl = lab_out / lf.name
        if not dstl.exists():
            dstl.symlink_to(lf)

    return img_out, lab_out


def find_plans_file(nnUNet_preprocessed_root: Path, dataset_id: int, plans_name: str) -> Path:
    pre_folder = find_dataset_folder(nnUNet_preprocessed_root, dataset_id)
    base = nnUNet_preprocessed_root / pre_folder
    candidates = [
        base / f"{plans_name}.json",
        base / "nnUNetPlans.json",
        base / "plans.json",
    ]
    candidates = [c for c in candidates if c.exists()]
    if candidates:
        return candidates[0]
    found = [p for p in base.glob("*.json") if p.is_file()]
    if not found:
        raise FileNotFoundError(f"No plans json found in {base}")
    return newest_file(found)


def extract_val_dice_from_summary(summary_json: Path) -> float:
    data = json.loads(summary_json.read_text())

    if isinstance(data, dict):
        fg = data.get("foreground_mean")
        if isinstance(fg, dict) and isinstance(fg.get("Dice"), (int, float)):
            return float(fg["Dice"])

        mean = data.get("mean")
        if isinstance(mean, dict):
            if isinstance(mean.get("Dice"), (int, float)):
                return float(mean["Dice"])
            dices = []
            for _, v in mean.items():
                if isinstance(v, dict) and isinstance(v.get("Dice"), (int, float)):
                    dices.append(float(v["Dice"]))
            if dices:
                return sum(dices) / len(dices)

    raise RuntimeError(f"Cannot parse Dice from summary: {summary_json}")


def predict_and_eval_val(default_results_root: Path,
                         model_dataset_id: int,
                         raw_data_root: Path,
                         nnUNet_preprocessed_root: Path,
                         dataset_id_for_val: int,
                         config: str,
                         trainer: str,
                         plans: str,
                         fold: int,
                         work_dir: Path,
                         np_eval: int,
                         overwrite: bool,
                         dry_run: bool) -> Tuple[Path, float]:
    val_cases = load_splits_val_cases(nnUNet_preprocessed_root, dataset_id_for_val, fold)
    img_dir, lab_dir = build_val_symlink_folders(raw_data_root, dataset_id_for_val, val_cases, work_dir / "valset", overwrite)

    pred_dir = work_dir / "pred"
    pred_dir.mkdir(parents=True, exist_ok=True)

    cmd_pred = [
        "nnUNetv2_predict",
        "-d", str(model_dataset_id),
        "-c", config,
        "-tr", trainer,
        "-p", plans,
        "-f", str(fold),
        "-chk", "checkpoint_final.pth",
        "-i", str(img_dir),
        "-o", str(pred_dir),
        "--disable_tta"
    ]
    run_cmd(cmd_pred, env=None, dry_run=dry_run)

    dataset_folder = find_dataset_folder(raw_data_root, dataset_id_for_val)
    djfile = raw_data_root / dataset_folder / "dataset.json"
    pfile = find_plans_file(nnUNet_preprocessed_root, dataset_id_for_val, plans)

    summary_json = work_dir / "summary.json"
    cmd_eval = [
        "nnUNetv2_evaluate_folder",
        "-djfile", str(djfile),
        "-pfile", str(pfile),
        "-o", str(summary_json),
        "-np", str(np_eval),
        str(lab_dir),
        str(pred_dir),
    ]
    run_cmd(cmd_eval, env=None, dry_run=dry_run)

    if dry_run:
        return summary_json, 0.0

    dice = extract_val_dice_from_summary(summary_json)
    return summary_json, dice


# =========================
# FedAvg core
# =========================
def extract_weights(ckpt: dict) -> Dict[str, torch.Tensor]:
    if "network_weights" in ckpt:
        return ckpt["network_weights"]
    if "state_dict" in ckpt:
        return ckpt["state_dict"]
    raise KeyError(f"Cannot find weights key in checkpoint. Keys={list(ckpt.keys())}")


def fedavg_state_dict(state_dicts: List[Dict[str, torch.Tensor]], weights: List[float]) -> Dict[str, torch.Tensor]:
    w = torch.tensor(weights, dtype=torch.float64)
    w = torch.clamp(w, min=1e-6)
    w = w / w.sum()

    keys0 = list(state_dicts[0].keys())
    for i, sd in enumerate(state_dicts[1:], start=1):
        if list(sd.keys()) != keys0:
            raise RuntimeError(f"State dict keys mismatch between client0 and client{i}")

    out: Dict[str, torch.Tensor] = {}
    for k in keys0:
        vals = [sd[k] for sd in state_dicts]
        v0 = vals[0]
        if torch.is_floating_point(v0):
            stacked = torch.stack([v.to(torch.float64) for v in vals], dim=0)
            flat = stacked.view(len(vals), -1)
            avg_flat = (w[:, None] * flat).sum(dim=0)
            out[k] = avg_flat.view_as(v0).to(v0.dtype)
        else:
            out[k] = v0
    return out


def make_global_ckpt(base_ckpt: dict, avg_weights: Dict[str, torch.Tensor]) -> dict:
    out = dict(base_ckpt)
    if "network_weights" in out:
        out["network_weights"] = avg_weights
    elif "state_dict" in out:
        out["state_dict"] = avg_weights
    else:
        out["network_weights"] = avg_weights
    for drop in ["optimizer_state", "grad_scaler_state"]:
        if drop in out:
            out[drop] = None
    return out


# =========================
# Generic export ID helpers
# =========================
def id_global(round_idx: int, global_id_offset: int) -> int:
    """Generate a generic nnU-Net dataset ID for an exported global model."""
    return global_id_offset + round_idx

def id_local(dataset_id: int, round_idx: int, local_id_multiplier: int) -> int:
    """Generate a generic nnU-Net dataset ID for an exported local client model."""
    return dataset_id * local_id_multiplier + round_idx

def folder_global(round_idx: int, global_id_offset: int) -> str:
    model_id = id_global(round_idx, global_id_offset)
    return f"Dataset{model_id:03d}_global_round{round_idx:03d}"

def folder_local(dataset_id: int, round_idx: int, fold: int, local_id_multiplier: int) -> str:
    model_id = id_local(dataset_id, round_idx, local_id_multiplier)
    return f"Dataset{model_id:03d}_client{dataset_id}_local_round{round_idx:03d}_fold{fold}"


# =========================
# Training (robust, with fallback copy)
# =========================
def train_client_once(dataset_id: int,
                      config: str,
                      fold: int,
                      trainer: str,
                      plans: str,
                      global_init: Path,
                      isolated_results_root: Path,
                      default_results_root: Path,
                      raw_data_root: Path,
                      env_base: Dict[str, str],
                      train_extra: List[str],
                      overwrite_isolated: bool,
                      dry_run: bool) -> Path:
    """
    Run nnUNetv2_train for a client, targeting isolated_results_root via env override.
    If outputs are not found under isolated_results_root, fallback to default_results_root
    and COPY produced fold tree into isolated_results_root.
    Returns checkpoint path inside isolated_results_root tree.
    """
    isolated_results_root.mkdir(parents=True, exist_ok=True)
    env = dict(env_base)

    # Set multiple vars to be safe (some setups still read legacy RESULTS_FOLDER)
    env["nnUNet_results"] = str(isolated_results_root)
    env["RESULTS_FOLDER"] = str(isolated_results_root)

    cmd = [
        "nnUNetv2_train", str(dataset_id), config, str(fold),
        "-tr", trainer,
        "-p", plans,
        "-pretrained_weights", str(global_init),
    ]
    cmd += train_extra

    log_path = isolated_results_root.parent / "train.log"
    print(f"[LOG] training output -> {log_path}")

    if dry_run:
        print("[DRY RUN] nnUNetv2_train skipped")
        return isolated_results_root / "DUMMY_CHECKPOINT.pth"

    # run training with stdout/stderr captured
    with open(log_path, "w") as f:
        subprocess.run(cmd, env=env, stdout=f, stderr=subprocess.STDOUT, check=True)

    # 1) try pick checkpoint in isolated
    try:
        ckpt = pick_checkpoint_from_tree(isolated_results_root)
        print(f"[INFO] picked checkpoint in isolated -> {ckpt}")
        return ckpt
    except FileNotFoundError:
        pass

    # 2) fallback: find in default results root then copy fold tree to isolated
    print("[WARN] No checkpoint found under isolated results. Fallback to default results root and copy into isolated...")

    src_dataset_folder = find_dataset_folder(raw_data_root, dataset_id)
    src_cfg = nnunet_cfg_dir(default_results_root, src_dataset_folder, trainer, plans, config)
    src_fold = nnunet_fold_dir(src_cfg, fold)
    if not src_fold.exists():
        raise FileNotFoundError(
            f"Fallback also failed: fold dir not found in default results.\n"
            f"Expected: {src_fold}\n"
            f"Check that trainer, plans, config, and fold match the training command."
        )

    # Copy cfg+fold into isolated results under same dataset folder name
    dst_dataset_folder = src_dataset_folder
    dst_cfg = nnunet_cfg_dir(isolated_results_root, dst_dataset_folder, trainer, plans, config)
    if dst_cfg.exists():
        if overwrite_isolated:
            safe_rm_tree(dst_cfg.parent)
        else:
            raise FileExistsError(f"Isolated already has {dst_cfg.parent}; use --overwrite to allow.")
    dst_cfg.mkdir(parents=True, exist_ok=True)

    # cfg-level files
    for item in src_cfg.iterdir():
        if item.is_file():
            shutil.copy2(item, dst_cfg / item.name)
    # fold dir
    shutil.copytree(src_fold, nnunet_fold_dir(dst_cfg, fold))

    # ensure final exists in the copied fold dir
    ensure_checkpoint_final(nnunet_fold_dir(dst_cfg, fold))

    ckpt = pick_checkpoint_from_tree(isolated_results_root)
    print(f"[INFO] picked checkpoint after fallback-copy -> {ckpt}")
    return ckpt


# =========================
# Optional initialization from an existing all-fold model
# =========================
def auto_find_dataset_all_ckpt(default_results_root: Path,
                               raw_data_root: Path,
                               dataset_id: int,
                               trainer: str,
                               plans: str,
                               config: str) -> Path:
    dataset_folder = find_dataset_folder(raw_data_root, dataset_id)
    all_dir = nnunet_cfg_dir(default_results_root, dataset_folder, trainer, plans, config) / "all"
    if not all_dir.exists():
        raise FileNotFoundError(f"All-fold model directory not found: {all_dir}")

    # prefer best then final then latest
    for name in ["checkpoint_best.pth", "checkpoint_final.pth", "checkpoint_latest.pth"]:
        p = all_dir / name
        if p.exists():
            return p
    raise FileNotFoundError(f"No checkpoint found in {all_dir}")


# =========================
# Main
# =========================
@dataclass
class ClientEval:
    did: int
    model_id: int
    dice: float
    summary_json: Path


def main():
    ap = argparse.ArgumentParser()

    ap.add_argument("--fl_root", required=True,
                    help="Output directory for FL artifacts")
    ap.add_argument("--raw_data_root", required=True,
                    help="Path to nnU-Net raw data root containing DatasetXXX_* folders")
    ap.add_argument("--results_root", required=True,
                    help="Path to nnU-Net results root")
    ap.add_argument("--nnUNet_preprocessed", required=True,
                    help="Path to nnU-Net preprocessed root")

    ap.add_argument("--datasets", nargs="+", type=int, required=True,
                    help="Client dataset IDs, e.g. <ID1> <ID2> <ID3>")
    ap.add_argument("--rounds", type=int, required=True,
                    help="Number of federated learning rounds")

    ap.add_argument("--config", required=True,
                    help="nnU-Net configuration, e.g. 2d, 3d_fullres")
    ap.add_argument("--trainer", required=True,
                    help="Trainer class name used for all clients")
    ap.add_argument("--plans", default="nnUNetPlans",
                    help="Plans name used for all clients")
    ap.add_argument("--fold", type=int, default=0,
                    help="Fold index used for local training and validation")

    ap.add_argument("--init_global", default="",
                    help="Initial global checkpoint for round 0 (.pth)")
    ap.add_argument("--init_from_dataset_all", type=int, default=None,
                    help="Optional dataset ID whose 'all' fold checkpoint is used as round-0 initialization if --init_global is not provided")
    ap.add_argument("--round1_weight", choices=["cases", "dice"], default="cases")
    ap.add_argument("--np_eval", type=int, default=4)

    ap.add_argument("--train_extra", nargs="*", default=[],
                    help="Additional arguments passed directly to nnUNetv2_train")
    ap.add_argument("--global_id_offset", type=int, default=100,
                    help="Exported global model dataset ID offset: global_id = offset + round")
    ap.add_argument("--local_id_multiplier", type=int, default=1000,
                    help="Exported local model dataset ID formula: local_id = dataset_id * multiplier + round")
    ap.add_argument("--overwrite", action="store_true",
                    help="Allow overwriting exported Dataset<ID>_* folders in the results root")
    ap.add_argument("--overwrite_isolated", action="store_true", help="allow overwriting isolated scratch tree")
    ap.add_argument("--dry_run", action="store_true")

    args = ap.parse_args()

    fl_root = Path(args.fl_root).resolve()
    raw_root = Path(args.raw_data_root).resolve()
    default_results_root = Path(args.results_root).resolve()
    preprocessed_root = Path(args.nnUNet_preprocessed).resolve()

    for p in [fl_root, raw_root, default_results_root, preprocessed_root]:
        if not p.exists():
            raise FileNotFoundError(f"Path not found: {p}")

    env_base = dict(os.environ)

    # FL working dirs
    globals_dir = fl_root / "globals"
    locals_dir = fl_root / "locals"
    metrics_dir = fl_root / "metrics"
    rounds_dir = fl_root / "rounds"
    tmp_dir = fl_root / "tmp_val"
    for d in [globals_dir, locals_dir, metrics_dir, rounds_dir, tmp_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # ---- round-0 initialization
    if args.init_global.strip():
        init_global = Path(args.init_global).resolve()
        if not init_global.exists():
            raise FileNotFoundError(f"--init_global not found: {init_global}")
    elif args.init_from_dataset_all is not None:
        init_global = auto_find_dataset_all_ckpt(
            default_results_root,
            raw_root,
            args.init_from_dataset_all,
            args.trainer,
            args.plans,
            args.config,
        )
    else:
        raise ValueError(
            "Please provide either --init_global <checkpoint.pth> or "
            "--init_from_dataset_all <DATASET_ID>."
        )

    print(f"[INFO] global0 init weights -> {init_global}")

    # store a copy as global_round0.pth (optional but useful)
    global_prev = globals_dir / "global_round0.pth"
    if not args.dry_run:
        shutil.copy2(init_global, global_prev)
    else:
        global_prev = init_global

    # static case-count weights
    case_counts = {}
    for did in args.datasets:
        folder = find_dataset_folder(raw_root, did)
        case_counts[did] = count_cases_in_imagesTr(raw_root, folder)
    print("[INFO] case counts:", case_counts)

    # =========================
    # Rounds
    # =========================
    for r in range(1, args.rounds + 1):
        print("\n" + "=" * 90)
        print(f"[ROUND {r:02d}] start | init global: {global_prev}")
        print("=" * 90)

        local_snapshots: Dict[int, Path] = {}
        client_export_folders: Dict[int, str] = {}

        # ---- train each client -> snapshot -> export local
        for did in args.datasets:
            isolated_root = rounds_dir / f"round{r:02d}" / f"client{did}" / "isolated_nnUNet_results"
            isolated_root.mkdir(parents=True, exist_ok=True)

            ckpt_any = train_client_once(
                dataset_id=did,
                config=args.config,
                fold=args.fold,
                trainer=args.trainer,
                plans=args.plans,
                global_init=global_prev,
                isolated_results_root=isolated_root,
                default_results_root=default_results_root,
                raw_data_root=raw_root,
                env_base=env_base,
                train_extra=args.train_extra,
                overwrite_isolated=args.overwrite_isolated,
                dry_run=args.dry_run
            )

            # snapshot checkpoint used
            snap = locals_dir / f"round{r:02d}_client{did}.pth"
            if not args.dry_run:
                shutil.copy2(ckpt_any, snap)
            local_snapshots[did] = snap

            # export local into default results root with unique DatasetID
            dst_folder = folder_local(did, r, args.fold, args.local_id_multiplier)
            if not args.dry_run:
                dst_fold_dir = copy_model_tree(
                    src_results_root=isolated_root,
                    src_dataset_id=did,
                    raw_data_root=raw_root,
                    dst_results_root=default_results_root,
                    dst_dataset_folder=dst_folder,
                    trainer=args.trainer,
                    plans=args.plans,
                    config=args.config,
                    fold=args.fold,
                    overwrite=args.overwrite
                )
                # ensure checkpoint_final exists
                ensure_checkpoint_final(dst_fold_dir)

            client_export_folders[did] = dst_folder
            print(f"[ROUND {r:02d}] D{did} local exported -> {default_results_root}/{dst_folder}")

        # ---- evaluate local val dice
        client_dice: Dict[int, float] = {}
        for did in args.datasets:
            model_id = id_local(did, r, args.local_id_multiplier)
            work = tmp_dir / f"round{r:02d}" / f"D{did}"
            summary_json, dice = predict_and_eval_val(
                default_results_root=default_results_root,
                model_dataset_id=model_id,
                raw_data_root=raw_root,
                nnUNet_preprocessed_root=preprocessed_root,
                dataset_id_for_val=did,
                config=args.config,
                trainer=args.trainer,
                plans=args.plans,
                fold=args.fold,
                work_dir=work,
                np_eval=args.np_eval,
                overwrite=True,
                dry_run=args.dry_run
            )
            client_dice[did] = dice

            outj = metrics_dir / f"round{r:02d}_D{did}_val.json"
            if not args.dry_run:
                outj.write_text(json.dumps({
                    "round": r,
                    "dataset_id": did,
                    "model_id": model_id,
                    "val_dice": dice,
                    "summary_json": str(summary_json)
                }, indent=2))

            print(f"[ROUND {r:02d}] D{did} val dice = {dice:.6f}")

        # ---- aggregation weights
        if r == 1 and args.round1_weight == "cases":
            weights = [float(case_counts[did]) for did in args.datasets]
            print(f"[ROUND {r:02d}] aggregation weights = case-count")
        else:
            weights = [float(max(client_dice[did], 1e-6)) for did in args.datasets]
            print(f"[ROUND {r:02d}] aggregation weights = val-dice")

        # ---- FedAvg -> global_round{r}.pth
        if args.dry_run:
            print("[DRY RUN] skip FedAvg + export global")
            continue

        ckpts = [torch.load(local_snapshots[did], map_location="cpu") for did in args.datasets]
        sds = [extract_weights(c) for c in ckpts]
        avg_sd = fedavg_state_dict(sds, weights)
        global_obj = make_global_ckpt(ckpts[0], avg_sd)

        global_path = globals_dir / f"global_round{r}.pth"
        torch.save(global_obj, global_path)
        print(f"[ROUND {r:02d}] global saved -> {global_path}")

        # ---- export global into the results root with a generic generated dataset ID
        template_folder = client_export_folders[args.datasets[0]]
        g_folder = folder_global(r, args.global_id_offset)
        export_global_from_template(
            global_ckpt=global_path,
            template_dataset_folder=template_folder,
            results_root=default_results_root,
            new_dataset_folder=g_folder,
            trainer=args.trainer,
            plans=args.plans,
            config=args.config,
            fold=args.fold,
            overwrite=args.overwrite
        )
        print(f"[ROUND {r:02d}] global exported -> {default_results_root}/{g_folder}")

        print("[PREDICT EXAMPLE]")
        print(
            f"  nnUNetv2_predict -d {id_global(r, args.global_id_offset)} -c {args.config} -tr {args.trainer} -p {args.plans} -f {args.fold} "
            f"-chk checkpoint_final.pth -i <imagesTs> -o <out_pred> --disable_tta"
        )

        global_prev = global_path

    print("\n[DONE]")


if __name__ == "__main__":
    main()
